# Generated by Django 3.1.4 on 2021-01-13 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='product_logos')),
                ('about', models.TextField()),
                ('ingredients', models.ManyToManyField(to='product.Ingredient')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
