# Generated by Django 3.1.4 on 2021-01-17 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
        ('order', '0003_auto_20210115_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='basket',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='basket', to='basket.basket'),
        ),
    ]
