# Generated by Django 3.1.4 on 2021-01-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210117_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
