# Generated by Django 3.1.4 on 2021-01-20 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_auto_20210118_1906'),
        ('order', '0005_order_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='instructions',
        ),
        migrations.AlterField(
            model_name='order',
            name='basket',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='basket.basket'),
        ),
    ]
