# Generated by Django 3.1.4 on 2021-05-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_localorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='localorder',
            name='poid',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='localorder',
            name='token',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='localorder',
            name='user_email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
