# Generated by Django 3.1.4 on 2021-05-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20210522_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='localorder',
            name='status',
            field=models.CharField(choices=[('PAID', 'PAID'), ('OPEN', 'OPEN'), ('STALE', 'STALE'), ('DECLINED', 'DECLINED')], default='OPEN', max_length=20),
        ),
        migrations.AddField(
            model_name='localorder',
            name='xcelid',
            field=models.CharField(default=0, max_length=24),
            preserve_default=False,
        ),
    ]
