# Generated by Django 3.1.4 on 2021-05-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_remove_localorder_xcelfooid'),
    ]

    operations = [
        migrations.AddField(
            model_name='localorder',
            name='totalcheckout',
            field=models.CharField(default=0, max_length=24),
        ),
    ]
