# Generated by Django 3.1.4 on 2021-05-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_localorder_totalcheckout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='account',
        ),
        migrations.AddField(
            model_name='customuser',
            name='xcelid',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
    ]
