# Generated by Django 3.1.4 on 2021-05-26 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_localaccount'),
        ('order', '0013_auto_20210526_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='xcelid',
        ),
        migrations.AddField(
            model_name='customuser',
            name='account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.account'),
        ),
    ]
