# Generated by Django 3.1.4 on 2021-01-17 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('instructions', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('PAID', 'PAID'), ('OPEN', 'OPEN'), ('DELETED', 'DELETED'), ('PROCESSED', 'DELETED')], default='OPEN', max_length=20)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='baskets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
