# Generated by Django 3.1.4 on 2021-01-18 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_auto_20210117_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='owner',
            new_name='user',
        ),
    ]
