# Generated by Django 3.1.4 on 2021-01-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_auto_20210118_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='status',
            field=models.CharField(choices=[('PAID', 'PAID'), ('OPEN', 'OPEN'), ('STALE', 'STALE'), ('DECLINED', 'DECLINED')], default='OPEN', max_length=20),
        ),
    ]
