# Generated by Django 3.1.4 on 2021-03-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0004_auto_20210125_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='poid',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='basket',
            name='token',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
    ]
