# Generated by Django 3.1.4 on 2021-05-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0005_auto_20210305_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalBasketPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PAID', 'PAID'), ('OPEN', 'OPEN'), ('STALE', 'STALE'), ('DECLINED', 'DECLINED')], default='OPEN', max_length=20)),
                ('token', models.CharField(blank=True, default='', max_length=24)),
                ('poid', models.CharField(blank=True, default='', max_length=24)),
                ('user_email', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
