# Generated by Django 3.1.4 on 2020-12-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('instructions', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('PAID', 'paid'), ('OPEN', 'open'), ('PROCESSED', 'processed')], max_length=20)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
