# Generated by Django 3.1.4 on 2020-12-28 19:08

from django.db import migrations, models
import xcel.order.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PAID', 'paid'), ('OPEN', 'open'), ('PROCESSED', 'processed')], default=xcel.order.models.OrderStatuses['OPEN'], max_length=20),
        ),
    ]
