# Generated by Django 3.1.4 on 2021-01-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('firstname', models.CharField(default='', max_length=200)),
                ('lastname', models.CharField(default='', max_length=200)),
                ('address_line_1', models.CharField(default='', max_length=200)),
                ('address_line_2', models.CharField(blank=True, default='', max_length=200)),
                ('country', models.CharField(default='', max_length=200)),
                ('postcode', models.CharField(default='', max_length=200)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
