# Generated by Django 3.1.4 on 2021-01-17 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='customer',
        ),
    ]
