# Generated by Django 3.1.4 on 2021-05-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('firstname', models.CharField(default='', max_length=200)),
                ('lastname', models.CharField(default='', max_length=200)),
                ('address_line_1', models.CharField(default='', max_length=200)),
                ('address_line_2', models.CharField(blank=True, default='', max_length=200)),
                ('country', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=200)),
                ('postcode', models.CharField(default='', max_length=200)),
                ('xcelid', models.CharField(default='', max_length=200)),
                ('poid', models.CharField(default='', max_length=200)),
                ('token', models.CharField(default='', max_length=200)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
